[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'

[rpc_endpoints]
arbitrum = "${ARBITRUM}"
mainnet = "${MAINNET}"

[fuzz]
seed = '20'

[profile.default.fuzz]
seed = '20'

# [profile.default.invariant]
# runs = 100
# depth = 100


# See more config options https://github.com/foundry-rs/foundry/tree/master/config